name: Terraform CI

on:
  pull_request:
    branches: [ "master" ]   # cambia a "master" si corresponde
    paths:
      - '**/*.tf'
      - 'environments/**'
      - '.github/workflows/github_workflows_terraform-ci.yml'

permissions:
  contents: write     # necesario para auto-commit en PRs del mismo repo
  pull-requests: write

jobs:
  terraform-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .   # raíz del repo

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0       # permite hacer commit de vuelta al branch del PR

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: "AKIA2CX35MSCBDLT5Q7R"
          aws-secret-access-key: "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"
          aws-region: "us-east-1"
          # aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      # 1) Intentar auto-formatear SIEMPRE
      - name: Terraform fmt (auto-fix)
        run: terraform fmt -recursive

      # 2) Intentar auto-commit (si es fork, puede no tener permisos; no rompemos el job acá)
      - name: Auto-commit fmt changes (best effort)
        uses: stefanzweifel/git-auto-commit-action@v5
        continue-on-error: true
        with:
          commit_message: "chore(fmt): apply terraform fmt via CI"
          file_pattern: "**/*.tf"

      # 3) Verificación: si sigue habiendo difs, fallamos (en forks el autor debe formatear localmente)
      - name: Terraform fmt (check + diff)
        run: terraform fmt -check -diff -recursive

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: |
          terraform plan -input=false -no-color \
            -var-file=environments/free-tier/terraform.tfvars \
            -out=tfplan.binary

      - name: Show plan
        run: terraform show -no-color tfplan.binary > plan.txt

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-free-tier
          path: plan.txt

      - name: Comentar plan en el PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: plan.txt
